config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: 'garages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :garages do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: %i[index edit update] do
    resources :reviews, only: %i[new create show]
  end

  get '/user_garages', to: 'garages#list'
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :user

  has_many :rentals, dependent: :destroy
  has_many :reviews, through: :rentals
  has_many_attached :photos

  validates :user_id, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :address, presence: true

  def rating
    return nil if reviews.reject(&:nil?).empty?

    (reviews.inject(0.0) { |sum, review| sum + review.rating unless review.nil? } / reviews.reject(&:nil?).count).round
  end

  # inclusao das definicoes do GEOcoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_garage, only: %i[show edit update destroy]
  after_action :authorize_garage, except: %i[index list]

  def index
    # @garages = policy_scope(Garage).select do |garage|
    #   garage.rentals.select do |rental|
    #     rental.start_date <= Date.today && (rental.end_date.nil? || rental.end_date >= Date.today)
    #   end.empty?
    # end
    @garages = policy_scope(Garage).select { |garage| garage.rentals.select { |rental| rental.end_date.nil? }.empty? }
    # Configuracao do MAPA:
    @markers = @garages.reject { |garage| garage.geocode.nil? }
                       .map do |garage|
      {
        lat: garage.geocode[0],
        lng: garage.geocode[1],
        infoWindow: render_to_string(partial: "garage_details", locals: { garage: garage }),
        content: "R$#{garage.price.to_i}"
      }
    end
  end

  def show
    if @garage.rentals.select { |rental| rental.end_date.nil? }.any?
      @rental = @garage.rentals.select { |rental| rental.end_date.nil? }.first
    else
      @rental = Rental.new
    end
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)
    @garage.user = current_user
    if @garage.save
      redirect_to @garage, notice: 'Garage was successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @garage.update(garage_params)
      redirect_to @garage, notice: 'Garage was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @garage.destroy
    redirect_to user_garages_path, notice: 'Garage was successfully destroyed.'
  end

  def list
    @garages = policy_scope(Garage).where(user: current_user)
  end

  private

  def set_garage
    @garage = Garage.find(params[:id])
  end

  def garage_params
    params.require(:garage).permit(:title, :address, :price, :description, photos: [])
  end

  def authorize_garage
    authorize @garage
  end
end

app/views/garages/_form.html.erb
<%= simple_form_for @garage do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-rent" %>
  </div>
<% end %>
<br>
<%= link_to 'Back', garages_path %>

app/views/garages/_garage_details.html.erb
<h3><%= link_to garage.title, garage %></h3>
<p><%= garage.address %></p>

app/views/garages/edit.html.erb
<div class="container">
  <h1>Edit garage</h1>
  <%= render "form", garage: @garage %>
</div>

app/views/garages/index.html.erb
<div class="text-center m-3">
  <h4>
    <span class="moving-text" id="banner-typed-text"></span>
  </h4>
</div>

<div class="d-flex">

<%# box da esquerda - listagem das garagens %>
<div class="container">
  <div class="grid-cards m-3">
    <% @garages.each do |garage| %>
        <%= link_to garage do %>
          <div class="card-product">
            <% if garage.photos.attached? %> 
              <%= cl_image_tag garage.photos.first.key %>
            <% end %>
            <div class="card-product-infos">
              <h5><%= garage.title %></h5>
              <% if  garage.rating.nil? %>
                <p>Not rated yet</p>
              <% else %>
                <p><%= garage.rating %> star<%= 's' if garage.rating > 1 %></p>
              <% end %>
              <p><%= garage.address %></p>
              <div>
              <p id="price">R$ <%= sprintf('%.2f', garage.price).gsub('.', ',') %>/day</p>
              </div>
            </div><!-- Fim do Card-Product-infos-->
          </div><!-- Fim do Card-Product-->
        <% end %>
    <% end %>
  </div><!-- Fim do grid de Cards-->
</div>

<%# box da direita - mapa %>
<div id="map"
     style="width: 100%; 
            height: 100vh; 
            position: sticky;
            top: 0;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

</div>

app/views/garages/list.html.erb
<div class="container">

<h3>Your garages</h3>

<% if @garages.empty? %>
  <h5>You have submitted no garages yet! =(</h5>
<% else %>
  <div class="container">
    
      <div class="grid-cards">
        <% @garages.each do |garage| %>
          <div class="card-product list-card">
            <% if garage.photos.attached? %> 
              <%= cl_image_tag garage.photos.first.key %>
            <% end %>
            <div class="card-product-infos">
              <h5><%= link_to garage.title, garage %></h5>
              <% if garage.rentals.select { |rental| rental.end_date.nil? }.empty? %>
                <p class="garage-status available">Available</p>
              <% else %>
                <% rental = garage.rentals.select { |rental| rental.end_date.nil? }.first %>
                <p class="garage-status unavailable">Rented since <%= rental.start_date.strftime("%d/%m/%Y") %> by <%= rental.user.name %></p>
              <% end %>
              <p><%= "#{garage.rating} stars" %></p>
              <p><%= garage.address %></p>
              <p><%= garage.description %></p>
              <div>
                <p id="price">R$ <%= sprintf('%.2f', garage.price).gsub('.', ',') %>/day</p>
              </div>
            </div><!-- Fim do Card-Product-infos-->
          </div><!-- Fim do Card-Product-->
        <% end %>
      </div><!-- Fim do grid de Cards-->
  </div>
  <br>
<% end %>

<hr>
<a class="btn-rent" href="/garages/new">Rent out a garage</a>

</div>

<br>
<br>

app/views/garages/new.html.erb
<div class="container">
  <h1>New garage</h1>
  <%= render "form", garage: @garage %>
</div>

app/views/garages/show.html.erb
<div class="container m-3">

  <h2 class="text-center"> Garage details:</h2>
  <hr>
  <br>
  <h3><strong><%= @garage.title %></strong></h3>
  <% if @garage.photos.attached? %>
      <% @garage.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    <% end %>
  <% unless @garage.rating.nil? %>
    <h5><%= @garage.rating %> star<%= 's' if @garage.rating > 1 %></h5>
  <% end %>
  <br>
  <br>
  <p><span style="color: gray">Price:</span> R$ <%= sprintf('%.2f', @garage.price).gsub('.', ',') %>/day</p>
  <p><span style="color: gray">Address:</span> <%= @garage.address %></p>
  <p><span style="color: gray">Description:</span> <%= @garage.description %></p>
  <small><span style="color: gray">Owner:</span> <%= @garage.user.name %></small>
  <br>
  <br>
  <%# Se for o dono da garagem%>
  <% if policy(@garage).update? %>
    <% if @garage.rentals.select { |rental| rental.end_date.nil? }.empty? %>
      <em><p style="color: green">This garage is available.</p></em>
    <% else %>
      <% rental = @garage.rentals.select { |rental| rental.end_date.nil? }.first %>
      <p>Rented since <%= rental.start_date.strftime("%d/%m/%Y") %> by <%= rental.user.name %>.</p>
    <% end %>
    
    <a class="btn-rent" href="<%= edit_garage_path(@garage) %>">Edit garage details</a>
    <br>
    <br>
    <a class="btn-rent" rel="nofollow" data-method="delete" href="<%=@garage%>">Delete garage subscription</a>
    <br>
    <%# <br> %>
  <%# Se nao for o dono da garagem %>
  <% else %>
    <% if @garage.rentals.select { |rental| rental.end_date.nil? }.any? %>
      <% if current_user == @rental.user %>
        <p>Rented since <%= @rental.start_date.strftime("%d/%m/%Y") %>.</p>
        <%= simple_form_for @rental do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= f.date_field :end_date, as: :date, min: [@rental.start_date, Date.today].max, html5: true %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, value: 'End rental' %>
          </div>
        <% end %>
        <%= link_to "End rental", edit_garage_path(@garage) %>
      <% else %>
        <p>Sorry, this garage is unavailable. =(</p>
      <% end %>
    <% else %>
      <% if current_user %>
        <%= simple_form_for [@garage, @rental] do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= f.date_field :start_date, as: :date, min: Date.today, html5: true %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, value: 'Rent this garage' %>
          </div>
        <% end %>
      <% else %>
        <%= link_to 'Sign in to rent', user_session_path %>
      <% end %>
    <% end %>
  <% end %>

  <br>
  <h5>Reviews</h5>
  <% if @garage.reviews.empty? %>
    <p>No reviews submitted yet. =(</p>
  <% else %>
    <% @garage.reviews.each do |review| %>
      <h5><%=review.rating %> star<%= 's' if review.rating > 1 %></h5>
      <p><%= review.rental.user.name %></p>
      <p><%= review.content %></p>
      <br>
    <% end %>
  <% end %>

</div>