config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: 'garages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :garages do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: %i[index edit update] do
    resources :reviews, only: %i[new create show]
  end

  get '/user_garages', to: 'garages#list'
end

app/views/shared/_carousel.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "citymarks.jpg", class:"img-banner", alt:"city with marks"  %>
    </div>
    <div class="carousel-item ">
      <%= image_tag "parking.jpg", class:"img-banner", alt:"city with marks"  %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<div class="footer-session">
  <div>
    <!-- Team -->
    <footer class="page-footer font-small blue">
      <div class="footer-links">
        <p>Our Team</p>
        <a href="#">Denilson Nascimento</a><br>
        <a href="#">Eduardo Ritter</a><br>
        <a href="#">Pedro Ilton</a><br>
        <a href="#">Uellington Bonaparte</a>
      </div>

      <!-- Social -->
    <div class="footer-links social">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>

    </footer>
  </div>
</div>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon", id="nav-links">
  <%= link_to garages_path, class: "navbar-brand" do %>
    <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <div>
    <%= image_tag "newlogo_garage.png", id:"nav-logo" %>
    </div>
  <% end %>
    <h1 id="logo-description">GARAGE RENTALS</h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li id="btn-home" class="nav-item active">
          <%= link_to "Home", garages_path, class: "nav-link", style:"color: white;&:hover:$special_orange;"   %>
        </li>
        <li class="nav-item">
          <%= link_to "My rentals", rentals_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My garages", user_garages_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%# <i class="fa fa-user-circle avatar-icon" aria-hidden="true"></i> %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>