config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: 'garages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :garages do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: %i[index edit update] do
    resources :reviews, only: %i[new create show]
  end

  get '/user_garages', to: 'garages#list'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :garage

  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates_inclusion_of :start_date, in: Date.today..
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: %i[edit update]
  after_action :authorize_rental, except: :index

  # rentals_path
  def index
    @rentals = policy_scope(Rental)
  end

  def show
    redirect_to rentals_path
  end

  # new_garage_rental_path
  def new
    @rental = Rental.new
    @garage = Garage.find(params[:garage_id])
  end

  # garage_rentals_path
  def create
    @rental = Rental.new(rentals_params)
    @rental.user = current_user
    @rental.garage = Garage.find(params[:garage_id])

    if @rental.save
      redirect_to rentals_path # alterar para o show do Garage
      # redirect_to @rental.garage
    else
      redirect_to @rental.garage
    end
  end

  def edit
    # @rental = Rental.find(params[:id])
  end

  def update
    # @rental = Rental.find(params[:id])
    if @rental.update(rentals_params)
      redirect_to rentals_path, notice: 'Rental successfully ended.'
      # redirect_to @rental.garage
    else
      redirect_to @rental.garage
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rentals_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def authorize_rental
    authorize @rental
  end
end

app/views/rentals/_form.html.erb
<div class="container">
<h1>New Rental</h1>

<%= simple_form_for [@garage, @rental] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date, as: :date, min: Date.today, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<br>
<%= link_to 'Back', rentals_path %>
</div>

app/views/rentals/edit.html.erb
 <%= render 'form', rental: @rental %>

app/views/rentals/index.html.erb
<div class="container">
  <br>
  <h4 class="text-center"><%=  "#{current_user.name}'s rentals" %></h4> 
  <% @rentals.each do |rental| %>
  <div class="row">
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="card mt-2" style="width: 300px;">
        <% if rental.garage.photos.attached? %>
          <%= cl_image_tag rental.garage.photos.first.key, height: 300, width: 300, crop: :fill %>
        <% end %>
          <div class="card-body ">
            <h5 class="card-text"><strong><%= link_to rental.garage.title, rental.garage %></strong></h5>
            <p class="card-text"><%= "Start date: #{rental.start_date.strftime("%d/%m/%Y")}" %></p>
            <% if rental.end_date.nil? %>
              <p class="card-text">Ongoing rental</p>
              
            <% else %>
              <p class="card-text"><%= "End date: #{rental.end_date.strftime("%d/%m/%Y")}" %></p>
              <% if rental.review.nil? %>
                <%= link_to 'Add Rewiew', new_rental_review_path(rental), class:"btn btn-primary justify-items-center" %>
              <% else %>
                <p>Your rating: <%=rental.review.rating %> star<%= 's' if rental.review.rating > 1 %></p>
              <% end %>
            <% end %>
            
            <%# <%= link_to 'Edit', edit_rental_path(rental), class:"btn btn-primary" %>
          </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/rentals/new.html.erb
 <h1><%= @garage.title %></h1>
 <%= render 'form', rental: @rental %>